# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.113.100:3306/jwgl_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 232918
  # Redis 配置
  redis:
    host: 192.168.113.100
    port: 6379
    password:
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: org.hz.backend.model.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# MinIO 配置
minio:
  endpoint: http://192.168.113.100:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: jwgl-system

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# JWT 配置
jwt:
  secret: your-secret-key-for-jwgl-system-application-2025
  expiration: 86400000  # 一天(毫秒)
  header: Authorization
  token-prefix: Bearer 

# OpenAPI 配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: org.hz.backend.controller

# 日志配置
logging:
  level:
    root: info
    org.hz.backend: debug
  file:
    name: logs/application.log